const vm = require('node:vm');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const elements = {};
const el = id => elements[id] ||= {value:'',style:{},scrollIntoView(){}};
const context = {document:{addEventListener(){}, getElementById:el, querySelectorAll(){return []}}, console};
vm.createContext(context);
vm.runInContext(fs.readFileSync('assets/js/app.js','utf8') + '\nthis.app = App;',context);
const app = context.app;
app.selectedDomain = 'vibecode'; app.currentPlanId = 'qa-vibecode'; app.showToast = ()=>{}; app.today = ()=> '2026-09-23';
el('wiz-duration').value = '1'; el('wiz-minutes').value = '30'; el('wiz-days').value = 'mon,tue,wed,thu,fri';
app.generateAiPromptFromWizard();
let prompt = el('wiz-generated-prompt-box').value;
assert(prompt.includes('MỘT task setup đầu tiên, 15–20 phút'));
assert(prompt.includes('Tổng thời lượng: 1 tuần'));
assert(prompt.includes('Không tạo subtask tự động'));
for (const name of ['ARCHITECTURE.md','PLAN.md','SPEC.md','DESIGN.md']) assert(prompt.includes(name));
el('code-platform').value = 'Web PHP và MySQL'; el('code-deployment').value = 'Shared hosting';
el('code-project-state').value = 'Tiếp tục dự án hiện có'; el('code-progress').value = 'Đã có đăng nhập; làm tiếp trang ghi chú';
el('code-sprint').value = 'Tự chia sprint / chọn việc theo tiến độ';
app.applyDomainSetup = (domain,modal,setup)=>{app.domainDetails[domain]=setup;};
el('code-core-idea').value = 'AI Evals Web đánh giá benchmark prompt và output';
app.applyCodeSetup({preventDefault(){}});
app.generateAiPromptFromWizard(); prompt = el('wiz-generated-prompt-box').value;
assert(prompt.includes('AI Evals Web đánh giá benchmark prompt và output'));
assert(prompt.includes('Đã có đăng nhập; làm tiếp trang ghi chú'));
assert(prompt.includes('Tự chia sprint / chọn việc theo tiến độ'));
assert(prompt.includes('không yêu cầu tạo lại từ đầu'));
assert(prompt.includes('Shared hosting'));
(async()=>{
    app.apiFetch = async()=>({json:async()=>({success:true,markdown:fs.readFileSync('examples/coding-roadmap.md','utf8')})});
    let saved;
    app.savePlanMarkdown = async md=>{saved=md;};
    el('wiz-start-date').value='2026-09-23';
    await app.useInstantSampleForDomain();
    assert(saved.includes('# Week 1\n## Wednesday\n- [ ] Setup chung'));
    assert.equal((saved.match(/Setup chung/g)||[]).length,1);
    assert(!saved.includes('# Week 2'));
    assert.equal((saved.match(/^## (Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday)$/gm)||[]).length,5);
    console.log('PASS: One short setup, continuation context, self-managed sprint, shared hosting, and setup-first sample on a mid-week start');
})().catch(e=>{console.error(e);process.exit(1);});
