const vm=require('node:vm');
const fs=require('node:fs');
const assert=require('node:assert/strict');
let type='unknown';
const selected={};
const elements = { 'ielts-target-band': { value: 'IELTS 7.0' } };
const context={document:{getElementById: id => (id === 'ielts-test-type' ? { value: type } : (elements[id] || { value: '' })), querySelectorAll:selector=>{
    const name=selector.match(/name="([^"]+)"/)[1];return (selected[name]||[]).map(value=>({value}));
}}};
vm.createContext(context);
vm.runInContext(fs.readFileSync('assets/js/ielts.js','utf8')+'\nthis.ielts=Ielts;',context);
const ielts=context.ielts;
assert.equal(ielts.topics.length,10);
assert.equal(ielts.groups.task2.rows.length,5);
assert.equal(ielts.groups.reading.rows.length,11);
assert(!ielts.prompt().includes('Khung: Introduction'));
assert(ielts.prompt().includes('hỏi người dùng trước'));
type='academic';
selected['ielts-format-academic']=['Natural process','Man-made process'];
selected['ielts-format-task2']=['Discussion'];
selected['ielts-topic']=['Education','Environment'];
let prompt=ielts.prompt();
assert(prompt.includes('Mục tiêu điểm số IELTS: IELTS 7.0'));
assert(prompt.includes('Natural process:'));
assert(prompt.includes('Man-made process:'));
assert(!prompt.includes('Formal letter:'));
assert(prompt.includes('Chủ đề ưu tiên: Education, Environment'));
assert(prompt.includes('Discussion:'));
assert(!prompt.includes('Opinion:'));
type='general';
prompt=ielts.prompt();
assert(prompt.includes('General Training'));
assert(prompt.includes('Formal letter:'));
assert(!prompt.includes('Natural process:'));
assert(!prompt.includes('Man-made process:'));
assert(prompt.includes('Multiple choice:'));
assert(prompt.includes('Part 3 — Discussion:'));
assert(prompt.includes('True / False / Not Given:'));
console.log('PASS: 10 topics, 5 Task 2 groups, all four skills, Academic processes, General letters, and selected priorities');
