<?php
/**
 * PlanParser — Parses PLAN.md files generated by ChatGPT or Gemini.
 * Extracts YAML frontmatter, goals, abilities, constraints, and weekly tasks.
 */
class PlanParser {

    /**
     * Parse markdown string into structured plan array
     */
    public static function parse(string $markdown): array {
        $markdown = str_replace(["\r\n", "\r"], "\n", $markdown);
        $markdown = trim($markdown);
        $markdown = preg_replace('/^```(?:markdown|md)?\s*\n(.*)\n```$/s', '$1', $markdown);

        $frontmatter = [];
        $content = $markdown;

        // 1. Extract YAML Frontmatter if present
        if (preg_match('/^---\s*\n(.*?)\n---\s*\n(.*)$/s', $markdown, $matches)) {
            $frontmatterRaw = $matches[1];
            $content = $matches[2];
            $frontmatter = self::parseSimpleYaml($frontmatterRaw);
        }

        // 2. Extract Sections (# Goal, # Current Ability, # Weak Areas, # Strong Areas, # Constraints)
        $sections = self::extractSections($content);

        // 3. Extract Weekly Plan (# Week X)
        $weeks = self::extractWeeks($content, $frontmatter['start_date'] ?? null);

        // Compute overall metadata
        $planId = $frontmatter['plan_id'] ?? '';
        $title = $frontmatter['title'] ?? ($sections['goal']['objective'] ?? 'Personal Plan');
        $version = $frontmatter['version'] ?? '1.0';
        $timezone = $frontmatter['timezone'] ?? 'Asia/Ho_Chi_Minh';
        $startDate = $frontmatter['start_date'] ?? date('Y-m-d');
        $durationWeeks = (int)($frontmatter['duration_weeks'] ?? count($weeks) ?: 1);

        $schedule = $frontmatter['schedule'] ?? [
            'days' => ['mon', 'tue', 'wed', 'thu', 'fri'],
            'daily_minutes' => 90
        ];

        // Flatten all tasks for quick indexing
        $allTasks = [];
        $totalMinutes = 0;
        foreach ($weeks as $weekNum => $weekData) {
            foreach ($weekData['days'] as $dayKey => $dayData) {
                foreach ($dayData['tasks'] as $t) {
                    $allTasks[$t['id']] = $t;
                    $totalMinutes += (int)($t['duration'] ?? 0);
                }
            }
        }

        return [
            'plan_id' => $planId,
            'title' => $title,
            'version' => $version,
            'timezone' => $timezone,
            'start_date' => $startDate,
            'current_date' => $frontmatter['current_date'] ?? date('Y-m-d'),
            'domain' => $frontmatter['domain'] ?? 'custom',
            'auto_delete_days' => isset($frontmatter['auto_delete_days']) ? (int)$frontmatter['auto_delete_days'] : null,
            'finance' => isset($frontmatter['finance_data']) && is_string($frontmatter['finance_data']) ? json_decode($frontmatter['finance_data'], true) : null,
            'duration_weeks' => $durationWeeks,
            'schedule' => $schedule,
            'goal' => $frontmatter['goal'] ?? [
                'type' => 'general',
                'description' => $sections['goal']['objective'] ?? $title
            ],
            'details' => [
                'objective' => $sections['goal']['objective'] ?? '',
                'current_level' => $sections['goal']['current_level'] ?? '',
                'target' => $sections['goal']['target'] ?? '',
                'deadline' => $sections['goal']['deadline'] ?? '',
                'abilities' => $sections['abilities'] ?? [],
                'weak_areas' => $sections['weak_areas'] ?? [],
                'strong_areas' => $sections['strong_areas'] ?? [],
                'constraints' => $sections['constraints'] ?? []
            ],
            'weeks' => $weeks,
            'task_count' => count($allTasks),
            'total_minutes' => $totalMinutes,
            'raw_markdown' => $markdown
        ];
    }

    /**
     * Simple YAML frontmatter parser (supports strings, numbers, lists, nested single level)
     */
    private static function parseSimpleYaml(string $yaml): array {
        $data = [];
        $lines = explode("\n", $yaml);
        $currentParent = null;

        foreach ($lines as $line) {
            $trimmed = trim($line);
            if ($trimmed === '' || str_starts_with($trimmed, '#')) continue;

            // Check indentation
            $indent = strlen($line) - strlen(ltrim($line));

            if ($indent > 0 && $currentParent !== null) {
                // Sub-property (e.g. description: ..., or days: [mon, tue])
                if (preg_match('/^([a-zA-Z0-9_\-]+)\s*:\s*(.*)$/', $trimmed, $subMatches)) {
                    $subKey = trim($subMatches[1]);
                    $subVal = self::cleanYamlVal($subMatches[2]);
                    $data[$currentParent][$subKey] = $subVal;
                }
                continue;
            }

            // Root property
            if (preg_match('/^([a-zA-Z0-9_\-]+)\s*:\s*(.*)$/', $trimmed, $m)) {
                $key = trim($m[1]);
                $valStr = trim($m[2]);

                if ($valStr === '') {
                    // Empty value means nested object start
                    $currentParent = $key;
                    $data[$key] = [];
                } else {
                    $currentParent = null;
                    $data[$key] = self::cleanYamlVal($valStr);
                }
            }
        }

        return $data;
    }

    /**
     * Clean and type-cast YAML scalar / list values
     */
    private static function cleanYamlVal(string $val) {
        $val = trim($val);
        // Strip quotes
        if ((str_starts_with($val, '"') && str_ends_with($val, '"')) ||
            (str_starts_with($val, "'") && str_ends_with($val, "'"))) {
            return substr($val, 1, -1);
        }
        // Array bracket format: [mon, tue, wed]
        if (str_starts_with($val, '[') && str_ends_with($val, ']')) {
            $inner = substr($val, 1, -1);
            $items = array_map('trim', explode(',', $inner));
            return array_values(array_filter($items, fn($x) => $x !== ''));
        }
        // Booleans
        if (strtolower($val) === 'true') return true;
        if (strtolower($val) === 'false') return false;
        // Numbers
        if (is_numeric($val)) return str_contains($val, '.') ? (float)$val : (int)$val;

        return $val;
    }

    /**
     * Extract Goal, Abilities, Constraints
     */
    private static function extractSections(string $content): array {
        $res = [
            'goal' => [],
            'abilities' => [],
            'weak_areas' => [],
            'strong_areas' => [],
            'constraints' => []
        ];

        // Parse # Goal section (stops at next level-1 header # or end of text)
        if (preg_match('/(?:^|\n)#\s+Goal\b(.*?)(?=\n#\s+[^#]|$)/si', $content, $m)) {
            $goalText = $m[1];
            if (preg_match('/##+\s+Objective\s*\n+([^#]+)/i', $goalText, $sub)) {
                $res['goal']['objective'] = trim($sub[1]);
            }
            if (preg_match('/##+\s+Current\s*Level\s*\n+([^#]+)/i', $goalText, $sub)) {
                $res['goal']['current_level'] = trim($sub[1]);
            }
            if (preg_match('/##+\s+Target\s*\n+([^#]+)/i', $goalText, $sub)) {
                $res['goal']['target'] = trim($sub[1]);
            }
            if (preg_match('/##+\s+Deadline\s*\n+([^#]+)/i', $goalText, $sub)) {
                $res['goal']['deadline'] = trim($sub[1]);
            }
        }

        // Parse # Current Ability
        if (preg_match('/(?:^|\n)#\s+Current\s+Ability(.*?)(?=\n#\s+[^#]|$)/si', $content, $m)) {
            $res['abilities'] = self::extractBulletPoints($m[1]);
        }
        // Parse # Weak Areas
        if (preg_match('/(?:^|\n)#\s+Weak\s+Areas(.*?)(?=\n#\s+[^#]|$)/si', $content, $m)) {
            $res['weak_areas'] = self::extractBulletPoints($m[1]);
        }
        // Parse # Strong Areas
        if (preg_match('/(?:^|\n)#\s+Strong\s+Areas(.*?)(?=\n#\s+[^#]|$)/si', $content, $m)) {
            $res['strong_areas'] = self::extractBulletPoints($m[1]);
        }
        // Parse # Constraints
        if (preg_match('/(?:^|\n)#\s+Constraints(.*?)(?=\n#\s+[^#]|$)/si', $content, $m)) {
            $res['constraints'] = self::extractBulletPoints($m[1]);
        }

        return $res;
    }

    private static function extractBulletPoints(string $text): array {
        $lines = explode("\n", $text);
        $points = [];
        foreach ($lines as $l) {
            $trimmed = trim($l);
            if (preg_match('/^[-*]\s+(.*)$/', $trimmed, $m)) {
                $points[] = trim($m[1]);
            }
        }
        return $points;
    }

    /**
     * Extract Weekly Plan (# Week X) -> (## Day) -> (- [ ] Task)
     */
    private static function extractWeeks(string $content, ?string $startDate): array {
        $weeks = [];

        // Split by # Week X or ## Week X
        $pattern = '/(?=(?:^|\n)#+\s+Week\s+(\d+))/i';
        $parts = preg_split($pattern, $content, -1, PREG_SPLIT_NO_EMPTY);

        try {
            $weekStartDt = $startDate ? new DateTime($startDate) : new DateTime();
        } catch (Exception $e) {
            $weekStartDt = new DateTime(); // Validator reports malformed dates.
        }
        $startWeekday = (int)$weekStartDt->format('N') - 1;

        $dayIndexMap = [
            'monday' => 0, 'mon' => 0,
            'tuesday' => 1, 'tue' => 1,
            'wednesday' => 2, 'wed' => 2,
            'thursday' => 3, 'thu' => 3,
            'friday' => 4, 'fri' => 4,
            'saturday' => 5, 'sat' => 5,
            'sunday' => 6, 'sun' => 6
        ];

        foreach ($parts as $part) {
            if (!preg_match('/^#+\s+Week\s+(\d+)(.*)$/si', trim($part), $wm)) {
                continue;
            }
            $weekNum = (int)$wm[1];
            $weekBody = $wm[2];

            $days = [];

            // Split by ## Day (Monday, Tuesday, etc.) or Day 1, Day 2
            $dayParts = preg_split('/(?=(?:^|\n)#{2,}\s+(?:Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday|Day\s+\d+))/i', $weekBody, -1, PREG_SPLIT_NO_EMPTY);

            foreach ($dayParts as $dayPart) {
                if (!preg_match('/^#{2,}\s+([A-Za-z0-9\s]+)\s*\n(.*)$/si', trim($dayPart), $dm)) {
                    continue;
                }
                $dayName = trim($dm[1]);
                $dayBody = $dm[2];

                // Determine calendar date for this day
                $dayLower = strtolower($dayName);
                $dayOffset = 0;
                if (isset($dayIndexMap[$dayLower])) {
                    $dayOffset = ($dayIndexMap[$dayLower] - $startWeekday + 7) % 7;
                }

                if (preg_match('/^day\s+(\d+)$/', $dayLower, $dayMatch)) {
                    $dayOffset = (int)$dayMatch[1] - 1;
                }

                // Calculate ISO date
                $calDate = clone $weekStartDt;
                $daysToAdd = (($weekNum - 1) * 7) + $dayOffset;
                $calDate->modify("+{$daysToAdd} days");
                $isoDate = $calDate->format('Y-m-d');

                $tasks = self::extractTasks($dayBody, $weekNum, $dayName);

                $days[$dayLower] = [
                    'day_name' => ucfirst($dayName),
                    'date' => $isoDate,
                    'tasks' => $tasks
                ];
            }

            $weeks[$weekNum] = [
                'week_number' => $weekNum,
                'days' => $days
            ];
        }

        return $weeks;
    }

    /**
     * Extract Tasks from day markdown block
     * Handles:
     * - [ ] Task Title
     *   - id: task-01
     *   - type: grammar
     *   - duration: 25
     *   - priority: high
     *   - target: 15
     *   - unit: words
     */
    private static function extractTasks(string $dayText, int $weekNum, string $dayName): array {
        $tasks = [];
        $lines = explode("\n", $dayText);
        $currentTask = null;

        foreach ($lines as $line) {
            $trimmed = trim($line);

            // Check if this line starts a task (- [ ] or - [x] or * [ ] or * [x])
            if (preg_match('/^[-*]\s*\[([ xX])\]\s*(.*?)$/', $trimmed, $tm)) {
                if ($currentTask !== null) {
                    $tasks[] = self::finalizeTask($currentTask, $weekNum, $dayName);
                }
                $isChecked = strtolower($tm[1]) === 'x';
                $title = trim($tm[2]);
                $currentTask = [
                    'title' => $title,
                    'checked_in_md' => $isChecked,
                    'props' => []
                ];
                continue;
            }

            // Task property line indented with 2+ spaces or tabs (e.g. - id: ..., - duration: 25)
            if ($currentTask !== null && preg_match('/^[-*]\s*([a-zA-Z0-9_\-]+)\s*:\s*(.*)$/', $trimmed, $pm)) {
                $propKey = strtolower(trim($pm[1]));
                $propVal = trim($pm[2]);
                $currentTask['props'][$propKey] = $propVal;
                continue;
            }
        }

        if ($currentTask !== null) {
            $tasks[] = self::finalizeTask($currentTask, $weekNum, $dayName);
        }

        return $tasks;
    }

    /**
     * Finalize task attributes and ensure required defaults
     */
    private static function finalizeTask(array $raw, int $weekNum, string $dayName): array {
        $props = $raw['props'];
        $title = $raw['title'];

        $id = $props['id'] ?? ('task-' . substr(md5($weekNum . '-' . $dayName . '-' . $title), 0, 8));
        $type = strtolower($props['type'] ?? 'custom');
        $duration = isset($props['duration']) ? (int)$props['duration'] : 25;
        $priority = strtolower($props['priority'] ?? 'medium');
        $target = isset($props['target']) ? (is_numeric($props['target']) ? (float)$props['target'] : $props['target']) : null;
        $unit = $props['unit'] ?? null;

        return [
            'id' => $id,
            'title' => $title,
            'type' => $type,
            'duration' => $duration,
            'priority' => $priority,
            'target' => $target,
            'unit' => $unit,
            'checked_in_md' => $raw['checked_in_md'],
            'status' => $props['status'] ?? ($raw['checked_in_md'] ? 'completed' : 'pending'),
            'actual_minutes' => isset($props['actual_minutes']) ? (int)$props['actual_minutes'] : ($raw['checked_in_md'] ? $duration : 0),
            'completed_at' => $props['completed_at'] ?? null,
            'subtasks' => isset($props['subtasks']) ? json_decode($props['subtasks'], true) : [],
            'description' => isset($props['description']) ? (json_decode($props['description'], true) ?? $props['description']) : '',
            'note_cards' => isset($props['note_cards']) ? json_decode($props['note_cards'], true) : null,
            'notes' => isset($props['note']) ? (json_decode($props['note'], true) ?? trim($props['note'], '"')) : ''
        ];
    }
}
